# Generated by Django 2.1.2 on 2018-10-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='baofei',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zcid', models.CharField(max_length=20, unique=True)),
                ('bfyy', models.CharField(max_length=200)),
                ('beizhu', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='czjl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zcid', models.CharField(max_length=20)),
                ('optuser', models.IntegerField()),
                ('opts', models.CharField(max_length=10)),
                ('czrq', models.DateTimeField()),
                ('beizhu', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='depts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='gdzc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zcid', models.CharField(max_length=20, unique=True)),
                ('zcm', models.CharField(max_length=20)),
                ('zcxh', models.CharField(max_length=20)),
                ('zxlb', models.CharField(max_length=20)),
                ('ccrq', models.DateField()),
                ('rkrq', models.DateField()),
                ('user', models.IntegerField()),
                ('stat', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('cost', models.IntegerField()),
                ('beizhu', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='jcwx',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zcid', models.CharField(max_length=20)),
                ('opts', models.CharField(max_length=10)),
                ('optuser', models.IntegerField()),
                ('xgry', models.IntegerField()),
                ('ckrq', models.DateField()),
                ('rkrq', models.DateField()),
                ('beizhu', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=20, unique=True)),
                ('upasswd', models.CharField(max_length=50)),
                ('udept', models.IntegerField()),
                ('addass', models.IntegerField()),
                ('delass', models.IntegerField()),
                ('wxass', models.IntegerField()),
                ('jhass', models.IntegerField()),
                ('beizhu', models.CharField(max_length=150)),
            ],
        ),
    ]
